### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ketancmaheshwari** [RMGDFT/rmgdft#11]
While building rmg latest git version on a Centos 7.4 x86 platform with intel 18.0.0 compilers, I get the following error while make:

/swtree/mod-condo/rmg/4.0.0/centos7.5_intel18.0.0/rmg-release_4.0.0/TDDFT/Common/Main.cpp(253): error: identifier "orbital_comm" is undefined
      orbital_comm(states);
      ^

Could you help resolving this.

**Comment by elbriggs** [comment]
Did you specify a specific target when typing make or just make with no target? There are several targets available and it looks like the problem is coming with the TDDFT branch. If you specify the base code does it build properly?
e.g.
make -jN rmg-cpu
with N being the number of cores you want to use in the build.

#        rmg-cpu        Base code cpu only
#        rmg-gpu        Base code with gpu support
#        rmg-on-cpu     ON code cpu only
#        rmg-on-gpu     ON code with gpu support
#        rmg-negf-cpu   Non equilibrium greens function code cpu only
#        rmg-negf-gpu   Non equilibrium greens function code with gpu support
#        rmg-tddft-cpu  TDDFT based on rmg-on cpu only
#        rmg-tddft-gpu  TDDFT based on rmg-on with gpu support

**Comment by ketancmaheshwari** [comment]
Thanks. Make rmg-cpu works and generates the binary. However, make install doesn't work -- throws back the same error. Is the whole thing supposed to be just that binary?

**Comment by elbriggs** [comment]
Yes you can run with just that binary. Make install will try to build with all of the modules and if one fails it stops but you should be able to manually put the binary where you want to run from.

**Comment by ketancmaheshwari** [comment]
Thank you.
